# Tugas 3
## CSM (Conventional and Social Media Movies) Dataset 2014 and 2015
### Pre-processing Data
### a. Missing Value

In [1]:
import pandas as pd
import numpy as np

In [2]:
datacsm = pd.read_csv("E:\Kuliah\Semester 6\DATMIN\Data Transformasi_06211640000001\CSM dataset 2014 and 2015.csv")
np.sum(datacsm.isnull())

Movie                   0
Year                    0
Gross                   0
Ratings                 0
Budget                  1
Screens                 9
Views                   0
Likes                   0
Dislikes                0
Comments                0
Aggregate Followers    21
dtype: int64

In [3]:
datacsmdes=datacsm.drop(['Movie','Year'],1)
datacsmdes.describe()

Gross     Ratings        Budget      Screens         Views  \
count  2.170000e+02  217.000000  2.160000e+02   208.000000  2.170000e+02   
mean   6.951567e+07    6.432719  4.833795e+07  2194.009615  3.645243e+06   
std    9.032310e+07    0.986618  5.522159e+07  1475.692020  4.545042e+06   
min    2.470000e+03    3.100000  7.000000e+04     2.000000  6.980000e+02   
25%    8.090000e+06    5.800000  8.983195e+06   429.000000  5.951940e+05   
50%    3.930000e+07    6.500000  2.650000e+07  2777.000000  2.389347e+06   
75%    9.040000e+07    7.100000  6.500000e+07  3373.000000  5.085068e+06   
max    6.430000e+08    8.700000  2.500000e+08  4324.000000  3.262678e+07   

               Likes      Dislikes      Comments  Aggregate Followers  
count     217.000000    217.000000    217.000000         1.960000e+02  
mean    12638.557604    662.511521   1795.562212         3.038193e+06  
std     29586.225415   1248.918655   3636.194147         4.886278e+06  
min         1.000000      0.000000      0.000000         1.066000e+03  
25%      1606.000000    105.000000    239.000000         1.830250e+05  
50%      5858.000000    336.000000    797.000000         1.052600e+06  
75%     14684.000000    689.000000   2046.000000         3.694500e+06  
max    370552.000000  13960.000000  38363.000000         3.103000e+07

In [4]:
datacsm['Budget']=datacsm['Budget'].fillna(datacsm['Budget'].mean())
datacsm['Screens']=datacsm['Screens'].fillna(datacsm['Screens'].mean())
datacsm['Aggregate Followers']=datacsm['Aggregate Followers'].fillna(datacsm['Aggregate Followers'].mean())
np.sum(datacsm.isnull())

Movie                  0
Year                   0
Gross                  0
Ratings                0
Budget                 0
Screens                0
Views                  0
Likes                  0
Dislikes               0
Comments               0
Aggregate Followers    0
dtype: int64

In [5]:
datacsmnomiss = datacsm
datacsmnomiss.head()

Movie  Year      Gross  Ratings       Budget  Screens  \
0                 13 Sins  2014       9130      6.3    4000000.0     45.0   
1          22 Jump Street  2014  192000000      7.1   50000000.0   3306.0   
2          3 Days to Kill  2014   30700000      6.2   28000000.0   2872.0   
3  300: Rise of an Empire  2014  106000000      6.3  110000000.0   3470.0   
4       A Haunted House 2  2014   17300000      4.7    3500000.0   2310.0   

     Views  Likes  Dislikes  Comments  Aggregate Followers  
0  3280543   4632       425       636            1120000.0  
1   583289   3465        61       186           12350000.0  
2   304861    328        34        47             483000.0  
3   452917   2429       132       590             568000.0  
4  3145573  12163       610      1082            1923800.0

In [6]:
datacsmnomiss.to_excel('CSM dataset 2014 and 2015 tanpa missing value.xlsx')

### b. Missing Value, Outlier

In [7]:
from scipy import stats
data1=datacsm.drop(['Movie','Year'],1)
z = np.abs(stats.zscore(data1._get_numeric_data()))
print(z)
datacsmnomissout=datacsm[(z<3).all(axis=1)]
print(datacsmnomissout.shape)

[[0.77131149 0.13483004 0.80663564 ... 0.19061344 0.3196318  0.41412055]
 [1.35920415 0.67789549 0.03023744 ... 0.48273945 0.44367371 2.01033451]
 [0.43073603 0.23642073 0.37000621 ... 0.50440813 0.48198888 0.55164307]
 ...
 [0.7699591  0.84596488 0.7975392  ... 0.05016824 0.18535659 0.15237723]
 [0.76998129 0.88107687 0.80663564 ... 0.5092234  0.49108528 0.62806846]
 [0.77023652 0.13483004 0.85211788 ... 0.51002594 0.48336712 0.39943997]]
(198, 11)


In [8]:
datacsmnomissout.head(10)

Movie  Year      Gross  Ratings       Budget  \
0                             13 Sins  2014       9130      6.3    4000000.0   
1                      22 Jump Street  2014  192000000      7.1   50000000.0   
2                      3 Days to Kill  2014   30700000      6.2   28000000.0   
3              300: Rise of an Empire  2014  106000000      6.3  110000000.0   
4                   A Haunted House 2  2014   17300000      4.7    3500000.0   
5                      A Long Way Off  2014      29000      4.6     500000.0   
6   A Million Ways to Die in the West  2014   42600000      6.1   40000000.0   
7                 A Most Violent Year  2014    5750000      7.1   20000000.0   
8         A Walk Among the Tombstones  2014   26000000      6.5   28000000.0   
11                     And So It Goes  2014   15200000      5.7   30000000.0   

        Screens    Views  Likes  Dislikes  Comments  Aggregate Followers  
0     45.000000  3280543   4632       425       636            1120000.0  
1   3306.000000   583289   3465        61       186           12350000.0  
2   2872.000000   304861    328        34        47             483000.0  
3   3470.000000   452917   2429       132       590             568000.0  
4   2310.000000  3145573  12163       610      1082            1923800.0  
5   2194.009615    91137    112         7         1             310000.0  
6   3158.000000  3013011   9595       419      1020            8153000.0  
7    818.000000  1854103   2207       197       593             130655.0  
8   2714.000000  2213659   2210       419       382             125646.0  
11  1762.000000   519327    963        94        70             386400.0

In [9]:
datacsmnomissout.to_excel('CSM dataset 2014 and 2015 tanpa missing value, outlier.xlsx')

### c.Missing Value, Transformasi

In [10]:
x = datacsm.iloc[0:217,2:11]
x.head()

Gross  Ratings       Budget  Screens    Views  Likes  Dislikes  \
0       9130      6.3    4000000.0     45.0  3280543   4632       425   
1  192000000      7.1   50000000.0   3306.0   583289   3465        61   
2   30700000      6.2   28000000.0   2872.0   304861    328        34   
3  106000000      6.3  110000000.0   3470.0   452917   2429       132   
4   17300000      4.7    3500000.0   2310.0  3145573  12163       610   

   Comments  Aggregate Followers  
0       636            1120000.0  
1       186           12350000.0  
2        47             483000.0  
3       590             568000.0  
4      1082            1923800.0

In [11]:
#normalization
from sklearn.preprocessing import normalize
xnorm = normalize(x,norm='l2') #default norm L2 and max
xnorm = pd.DataFrame(xnorm)
xnorm.tail()

0             1         2         3         4         5         6  \
212  0.601194  7.314228e-07  0.713583  0.000003  0.359670  0.001641  0.000027   
213  0.194934  5.129855e-07  0.968403  0.000048  0.155553  0.000436  0.000079   
214  0.016892  7.220979e-07  0.580257  0.000010  0.655699  0.001852  0.000077   
215  0.032212  1.822874e-06  0.998835  0.000003  0.015912  0.000029  0.000007   
216  0.055297  3.286513e-06  0.782503  0.000011  0.023456  0.000057  0.000014   

            7         8  
212  0.000116  0.000197  
213  0.000088  0.000438  
214  0.000318  0.482774  
215  0.000003  0.032212  
216  0.000022  0.619743

In [12]:
# Softmax
## Softmax merupakan metode normalisasi pengembangan transformasi secara linier. 
## Metode ini sangat berguna pada saat data-data yang ada melibatkan data-data outlier.
def softmax(x):
    return np.exp(x)/np.sum(np.exp(x), axis = 0)
xsoft = softmax(xnorm)
xsoft = pd.DataFrame(xsoft)
print(xsoft)

            0         1         2         3         4         5         6  \
0    0.002337  0.004608  0.005237  0.004608  0.007650  0.004610  0.004609   
1    0.006128  0.004608  0.003163  0.004608  0.004128  0.004607  0.004608   
2    0.004883  0.004608  0.004826  0.004608  0.004147  0.004606  0.004608   
3    0.004669  0.004608  0.005054  0.004608  0.004128  0.004607  0.004608   
4    0.006089  0.004608  0.002987  0.004609  0.004901  0.004610  0.004608   
5    0.002449  0.004608  0.005692  0.004625  0.004796  0.004607  0.004608   
6    0.004797  0.004608  0.004841  0.004608  0.004332  0.004607  0.004608   
7    0.003072  0.004608  0.006407  0.004608  0.004498  0.004607  0.004608   
8    0.004601  0.004608  0.005112  0.004608  0.004361  0.004607  0.004608   
9    0.005652  0.004608  0.003089  0.004608  0.004526  0.004607  0.004608   
10   0.006253  0.004608  0.002903  0.004608  0.004162  0.004607  0.004608   
11   0.003665  0.004608  0.006001  0.004608  0.004180  0.004607  0.004608   

In [13]:
xsoft.to_excel('CSM dataset 2014 and 2015 tanpa missing value dan telah ditransformasikan.xlsx')

### d. Missing Value, Outlier, Transformasi

In [14]:
xx = datacsmnomissout.iloc[0:198,2:11]
xx.head()

Gross  Ratings       Budget  Screens    Views  Likes  Dislikes  \
0       9130      6.3    4000000.0     45.0  3280543   4632       425   
1  192000000      7.1   50000000.0   3306.0   583289   3465        61   
2   30700000      6.2   28000000.0   2872.0   304861    328        34   
3  106000000      6.3  110000000.0   3470.0   452917   2429       132   
4   17300000      4.7    3500000.0   2310.0  3145573  12163       610   

   Comments  Aggregate Followers  
0       636            1120000.0  
1       186           12350000.0  
2        47             483000.0  
3       590             568000.0  
4      1082            1923800.0

In [15]:
#normalization
from sklearn.preprocessing import normalize
xxnorm = normalize(xx,norm='l2') #default norm L2 and max
xxnorm = pd.DataFrame(xxnorm)
xxnorm.tail()

0             1         2         3         4         5         6  \
193  0.601194  7.314228e-07  0.713583  0.000003  0.359670  0.001641  0.000027   
194  0.194934  5.129855e-07  0.968403  0.000048  0.155553  0.000436  0.000079   
195  0.016892  7.220979e-07  0.580257  0.000010  0.655699  0.001852  0.000077   
196  0.032212  1.822874e-06  0.998835  0.000003  0.015912  0.000029  0.000007   
197  0.055297  3.286513e-06  0.782503  0.000011  0.023456  0.000057  0.000014   

            7         8  
193  0.000116  0.000197  
194  0.000088  0.000438  
195  0.000318  0.482774  
196  0.000003  0.032212  
197  0.000022  0.619743

In [16]:
# Softmax
def softmax(xx):
    return np.exp(xx)/np.sum(np.exp(xx), axis = 0)
xxsoft = softmax(xxnorm)
xxsoft = pd.DataFrame(xxsoft)
print(xxsoft)

            0         1         2         3         4         5         6  \
0    0.002607  0.005051  0.005625  0.005050  0.008406  0.005054  0.005051   
1    0.006836  0.005051  0.003398  0.005050  0.004536  0.005049  0.005050   
2    0.005447  0.005051  0.005183  0.005050  0.004556  0.005049  0.005050   
3    0.005208  0.005051  0.005428  0.005050  0.004536  0.005049  0.005050   
4    0.006792  0.005051  0.003208  0.005051  0.005385  0.005053  0.005051   
5    0.002732  0.005051  0.006113  0.005069  0.005270  0.005050  0.005050   
6    0.005352  0.005051  0.005200  0.005050  0.004760  0.005050  0.005050   
7    0.003427  0.005051  0.006881  0.005050  0.004943  0.005050  0.005050   
8    0.005133  0.005051  0.005491  0.005050  0.004792  0.005049  0.005050   
9    0.004089  0.005051  0.006446  0.005050  0.004593  0.005049  0.005050   
10   0.005771  0.005051  0.004827  0.005050  0.004562  0.005049  0.005050   
11   0.003062  0.005051  0.007038  0.005050  0.005082  0.005049  0.005050   

In [17]:
xxsoft.to_excel('CSM dataset 2014 dan 2015 tanpa missing value dan outlier serta telah ditransformasikan.xlsx')